# Generated by Django 5.1.6 on 2025-03-26 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HardwareComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Название компонента"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CPU", "Процессор"),
                            ("GPU", "Видеокарта"),
                            ("RAM", "Оперативная память"),
                            ("SSD", "Накопитель SSD"),
                            ("HDD", "Жесткий диск"),
                            ("MB", "Материнская плата"),
                            ("PSU", "Блок питания"),
                        ],
                        max_length=3,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(max_length=100, verbose_name="Производитель"),
                ),
                (
                    "release_date",
                    models.DateField(blank=True, null=True, verbose_name="Дата выхода"),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Цена (USD)",
                    ),
                ),
                (
                    "power_consumption",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Потребляемая мощность (Вт)",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "in_stock",
                    models.BooleanField(default=True, verbose_name="В наличии"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Аппаратный компонент",
                "verbose_name_plural": "Аппаратные компоненты",
                "db_table": "hardware_components",
                "ordering": ["-created_at"],
            },
        ),
    ]
